{% set name = "pytest-golden" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-golden-{{ version }}.tar.gz
  sha256: 54e6f317a533758e6dcc96e6ef9457c610ae1c9db53575686a303f3ef7ad1e35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6.0,<4.0.0
    - pytest >=6.1.2
    - ruamel.yaml >=0.16.12,<1.0
    - atomicwrites >=1.4.0,<2.0.0
    - dataclasses >=0.7,<1.0
    - testfixtures >=6.15.0,<7.0.0

test:
  imports:
    - pytest_golden
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oprypin/pytest-golden
  summary: Plugin for pytest that offloads expected outputs to data files
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - fpaniagua
